export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export const ENUMS = {
  ROLES: {
    ADMIN: "admin",
    USER: "user",
  },
  AUTH_STATUS: {
    ACTIVE: "active",
    PENDING_VERIFICATION: "pending_verification",
    INACTIVE: "inactive",
    BLOCKED: "blocked",
    DELETED: "deleted",
  },
  CONTACT_METHODS: {
    EMAIL: "email",
    PHONE: "phone",
    SMS: "sms",
  },
  FOUNDER_WAITLIST_STATUS: {
    NOT_ON_LIST: "not_on_list",
    ON_WAITLIST: "on_waitlist",
  },
  FOUNDER_APPLICANT_STATUS: {
    NONE: "none",
    APPLIED: "applied",
    IN_PROGRESS: "in_progress",
    COMPLETED: "completed",
    CANCELLED: "cancelled",
    ON_HOLD: "on_hold",
  },
  FOUNDER_QUALIFICATION_STATUS: {
    NOT_STARTED: "not_started",
    PENDING_VERIFICATION: "pending_verification",
    PENDING_PROFILE: "pending_profile",
    PENDING_DISCLOSURES: "pending_disclosures",
    PENDING_ACTIVATION: "pending_activation",
    QUALIFIED: "qualified",
    DISQUALIFIED: "disqualified",
    EXPIRED: "expired",
  },
  FOUNDER_TIER: {
    NONE: "none",
    ESSENTIAL_100: "essential_100",
    EXPANDED_500: "expanded_500",
    PREMIUM_1000: "premium_1000",
  },
  SUCCESS_PROFILE_TYPE: {
    INDIVIDUAL: "individual",
    HOUSEHOLD: "household",
    GROUP: "group",
    PROFESSIONAL: "professional",
    BUSINESS: "business",
    ORGANIZATIONAL: "organizational",
  },
  SUCCESS_PROFILE_STATUS: {
    INCOMPLETE: "incomplete",
    COMPLETE: "complete",
  },
  DISCRETIONARY_RULE_LABEL: {
    WEALTH_PRESERVATION_10: "wealth_preservation_10",
    CONSERVATIVE_20: "conservative_20",
    MODERATE_30: "moderate_30",
    FLEXIBLE_40: "flexible_40",
    CUSTOM: "custom",
  },
  SUCCESS_CENTER_CATEGORY_STATUS: {
    ACTIVE: "active",
    INACTIVE: "inactive",
  },
  SUCCESS_CENTER_PROGRAM_STATUS: {
    PUBLISHED: "published",
    DRAFT: "draft",
    IN_DEVELOPMENT: "in_development",
    COMING_SOON: "coming_soon",
    INACTIVE: "inactive",
  },
  SUCCESS_CENTER_PROGRAM_TYPE: {
    FUNDING: "funding",
    PLANNING: "planning",
  },
  SUCCESS_CENTER_GOAL_NATURE: {
    ONE_TIME: "one_time",
    RECURING: "recurring",
  },
  FOUNDER_PLAN_NAME: {
    ESSENTIAL_100: "essential_100",
    EXPANDED_500: "expanded_500",
    PREMIUM_1000: "premium_1000",
  },
  FOUNDER_PLAN_PRIORITY_LEVEL: {
    STANDARD: "standard",
    HIGHER: "higher",
    PREMIUM: "premium",
  },
  FOUNDER_PLAN_BMIS_PLANNING_LEVEL: {
    STANDARD: "standard",
    EXPANDED: "expanded",
    PREMIUM: "premium",
  },
  FOUNDER_PLAN_STATUS: {
    ACTIVE: "active",
    INACTIVE: "inactive",
  },
  FOUNDER_PURCHASE_ACTIVATION_STATUS: {
    PENDING: "pending",
    COMPLETED: "completed",
    FAILED: "failed",
  },
  SUCCESS_CENTER_OBLIGATION_TYPE: {
    EXISTING_OBLIGATION: "existing_obligation",
    NEW_GOAL: "new_goal",
  },
  SUCCESS_CENTER_PRICING_SOURCE: {
    ESTIMATED: "estimated",
    VERIFIED: "verified",
  },
  SUCCESS_CENTER_PAYEE_TYPE: {
    LANDLORD: "landlord",
    LENDER: "lender",
    DEALER: "dealer",
    VENDOR: "vendor",
    PROVIDER: "provider",
    SELF: "self",
    OTHER: "other",
  },
  SUCCESS_CENTER_SELECTION_STATUS: {
    ACTIVE: "active",
    REMOVED: "removed",
  },
  RECOMMENDATION_LABEL: {
    FAST: "fast",
    MODERATE: "moderate",
    LONGER: "longer",
  },
  RECOMMENDATION_AFFORDABILITY_STATUS: {
    ELIGIBLE: "eligible",
    ELIGIBLE_WITH_ADJUSTMENT: "eligible_with_adjustment",
    BUILD_SAVINGS_FIRST: "build_savings_first",
    INCREASE_INCOME_FIRST: "increase_income_first",
    NOT_CURRENTLY_ELIGIBLE: "not_currently_eligible",
  },
  PROGRAM_CYCLE_REACTIVATION_STATUS: {
    NOT_DUE: "not_due",
    PENDING: "pending",
    COMPLETED: "completed",
    MISSED: "missed",
  },
  PROGRAM_CYCLE_AUTOMATIC_RENEWAL_RESULT: {
    RENEWED: "renewed",
    NOT_RENEWED: "not_renewed",
    PENDING: "pending",
  },
  PROGRAM_CYCLE_CURRENT_BMIS_STATUS: {
    PROJECTED: "projected",
    DEVELOPING: "developing",
    ON_TRACK: "on_track",
    RESERVE_SUPPORT_EXPECTED: "reserve_support_expected",
    AT_RISK: "at_risk",
    APPROVED: "approved",
    RELEASED: "released",
    PAUSED: "paused",
    RESTARTED: "restarted",
  },
  ACTIVATION_PROGRESS_FULL_UPFRONT_STATUS: {
    NOT_FULL_UPFRONT: "not_full_upfront",
    FULL_UPFRONT: "full_upfront",
  },
  ACTIVATION_PROGRESS_AVALANCHE_QUALIFICATION: {
    NOT_QUALIFIED: "not_qualified",
    QUALIFIED: "qualified",
  },
  ACTIVATION_PROGRESS_ELIGIBILITY_STATUS: {
    NOT_ELIGIBLE: "not_eligible",
    PENDING: "pending",
    ELIGIBLE: "eligible",
  },
  ACTIVATION_PROGRESS_FUNDING_ESTIMATE_STATUS: {
    PROJECTED: "projected",
    ESTIMATED: "estimated",
    CONFRIMED: "confrimed",
  },
  AVALANCHE_ELIGIBILITY: {
    ELIGIBLE: "eligible",
    INELIGIBLE: "ineligible",
  },
  AVALANCHE_QUEUE_STATUS: {
    NOT_QUEUED: "not_queued",
    QUEUED: "queued",
    IN_REVIEW: "in_review",
    APPROVED: "approved",
    RELEASED: "released",
  },
  AVALANCHE_BMIS_APPROVAL_STATUS: {
    PENDING: "pending",
    APPROVED: "approved",
    REJECTED: "rejected",
  },
  AVALANCHE_SYSTEM_CAPACITY_STATUS: {
    AVAILABLE: "available",
    CONSTRAINED: "constrained",
  },
  FOLLOW_ME_ALLOCATIONS_RELATIONSHIP_STATUS: {
    ACTIVE: "active",
    INACTIVE: "inactive",
    ENDED: "ended",
  },
  FOLLOW_ME_ALLOCATIONS_ENTRY_TYPE: {
    SIMULATION: "simulation",
    LIVE: "live",
  },
  SETTING_CATEGORY: {
    FOUNDER: "founder",
    ACTIVATION: "activation",
    ALLOCATION: "allocation",
    RESERVE: "reserve",
    PLATFORM_FEE: "platformFee",
    THRESHOLD: "threshold",
    DISCRETIONARY: "discretionary",
    PRICING: "pricing",
    AVALANCHE: "avalanche",
    FOLLOW_ME: "followMe",
    GROWTH_PERIOD: "growthPeriod",
    QUEUE: "queue",
    STATISTICAL_PRICING: "statisticalPricing",
  },
  SETTINGS_DATA_TYPE: {
    NUMBER: "number",
    PERCENTAGE: "percentage",
    OBJECT: "object",
    ARRAY: "array",
  },
  LEGAL_DOCUMENT_TYPE: {
    DISCLAIMER: "disclaimer",
    FOUNDING_DISCLOSURE: "founding_disclosure",
    TERMS: "terms",
    PRIVACY: "privacy",
    REFUND_POLICY: "refund_policy",
    CHECKOUT_ACKNOWLEDGMENT: "checkout_acknowledgment",
    SUCCESS_CENTER_NOTICE: "success_center_notice",
    PARTNER_DISCLOSURE: "partner_disclosure",
    OTHER: "other",
  },
  LEGAL_DOCUMENT_STATUS: {
    PENDING: "pending",
    PUBLISHED: "published",
    DRAFT: "draft",
  },
  LEGAL_ACCEPTANCE_CONTEXT: {
    SIGNUP: "signup",
    CHECKOUT: "checkout",
    FOUNDER_ACTIVATION: "founder_activation",
    OTHER: "other",
  },
  AUDIT_LOG_ACTION: {
    UPDATE_SETTING: "updated_setting",
    ADJUSTED_RECOMMENDATION: "adjusted_recommendation",
    PROCESSED_REFUND: "processed_refund",
    DEACTIVATED_CATEGORY: "deactivated_category",
    ASSIGNED_FOUNDER_NUMBER: "assigned_founder_number",
    QUALIFIED_FOUNDER: "qualified_founder",
  },
  AUDIT_LOG_TARGET_TYPE: {
    USER: "User",
    SUCCESS_PROFILE: "SuccessProfile",
    SUCCESS_CENTER_CATEGORY: "SuccessCenterCategory",
    SUCCESS_CENTER_PROGRAM: "SuccessCenterProgram",
    SUCCESS_CENTER_SELECTION: "SuccessCenterSelection",
    FOUNDER_PLAN: "FounderPlan",
    FOUNDER_PURCHASE: "FounderPurchase",
    RECOMMENDATION: "Recommendation",
    PROGRAM_CYCLE: "ProgramCycle",
    ACTIVATION_PROGRESS: "ActivationProgress",
    AVALANCHE_QUALIFICATION: "AvalancheQualification",
    BMIS_QUEUE: "BmisQueue",
    FOLLOW_ME_ALLOCATION: "FollowMeAllocation",
    SETTING: "Setting",
    LEGAL_DOCUMENT: "LegalDocument",
    LEGAL_ACCEPTANCE: "LegalAcceptance",
    AUDIT_LOG: "AuditLog",
    CONTENT_BLOCK: "ContentBlock",
    PAYMENT: "Payment",
    FINANCIAL_LEDGER: "FinancialLedger",
  },
  CONTENT_BLOCK_TYPE: {
    RICH_TEXT: "richtext",
    VIDEO: "video",
  },
  NOTIFICATION_TYPE: {
    RECOMENDATION_READY: "recommendation_ready",
    PAYMENT_RECIEVED: "payment_received",
    PROFILE_REMINDER: "profile_reminder",
    FOUNDER_STATUS: "founder_status",
    ANNOUNCEMENT: "announcement",
  },
  BMIS_QUEUE_TYPE: {
    RECURRING_MONTHLY: "recurring_monthly",
    ONE_TIME: "one_time",
    AVALANCHE: "avalanche",
    RESERVE_SUPPORTED: "reserve_supported",
    PRIORITY_FUNDING: "priority_funding",
    ADMIN_REVIEW: "admin_review",
  },
  BMIS_QUEUE_GROWTH_PERIOD_STATUS: {
    NOT_STARTED: "not_started",
    IN_PROGRESS: "in_progress",
    COMPLETED: "completed",
  },
  BMIS_QUEUE_FUNDING_STATUS: {
    PROJECTED: "projected",
    PENDING: "pending",
    APPROVED: "approved",
    RELEASED: "released",
    PAUSED: "paused",
  },
  BMIS_QUEUE_RESERVE_SUPPORT_STATUS: {
    NONE: "none",
    EXPECTED: "expected",
    APPLIED: "applied",
  },
  BMIS_QUEUE_CAP_STATUS: {
    WITHIN_CAP: "within_cap",
    AT_CAP: "at_cap",
    OVER_CAP: "over_cap",
  },
  BMIS_QUEUE_DECISION: {
    PENDING: "pending",
    APPROVED: "approved",
    DEFERRED: "deferred",
    REJECTED: "rejected",
  },
  PAYMENT_PROVIDER: {
    STRIPE: "stripe",
  },
  PAYMENT_STATUS: {
    PENDING: "pending",
    COMPLETED: "completed",
    FAILED: "failed",
  },
  PAYMENT_REFUND_STATUS: {
    NONE: "none",
    REQUESTED: "requested",
    APPROVED: "approved",
    COMPLETED: "completed",
  },
  PAYMENT_DISPUTE_STATUS: {
    NONE: "none",
    PAYMENT_DISPUTE: "payment_dispute",
    CHARGEBACK: "chargeback",
  },
  FINANCIAL_LEDGER_TRANSACTION_TYPE: {
    GROSS_ACTIVATION_REVENUE: "gross_activation_revenue",
    PRIMARY_FUNDING_ALLOCATION: "primary_funding_allocation",
    PROTECTED_RESERVE: "protected_reserve",
    SPILLOVER: "spillover",
    RESERVE_PARTICIPATION: "reserve_participation",
    PLATFORM_FEE: "platform_fee",
    REWARDS: "rewards",
    FOLLOWME_DIRECTED: "followme_directed",
    FOLLOWME_WIDER: "followme_wider",
    MONTHLY_PROGRAM_SUPPORT: "monthly_program_support",
    ONETIME_PROGRAM_SUPPORT: "onetime_program_support",
    AVALANCHE_SUPPORT: "avalanche_support",
    PARTICIPANT_OBLIGATION: "participant_obligation",
    FOUNDER_BENEFIT_OBLIGATION: "founder_benefit_obligation",
    REFUND: "refund",
    REFUND_REVERSAL: "refund_reversal",
    CHARGEBACK_REVERSAL: "chargeback_reversal",
    VENDOR_RELEASE: "vendor_release",
    CURRENCY_CONVERSION: "currency_conversion",
    ADMIN_ADJUSTMENT: "admin_adjustment",
  },
  FINANCIAL_LEDGER_APPROVAL_STATUS: {
    PENDING: "pending",
    APPROVED: "approved",
    REJECTED: "rejected",
  },
  FINANCIAL_LEDGER_ENTRY_TYPE: {
    SIMULATION: "simulation",
    LIVE: "live",
  },
};
